package com.ning.dao;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SalesLargeGoodsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_srv_sales_large_goods
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_srv_sales_large_goods
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_srv_sales_large_goods
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_srv_sales_large_goods
     *
     * @mbggenerated
     */
    public SalesLargeGoodsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_srv_sales_large_goods
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_srv_sales_large_goods
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_srv_sales_large_goods
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_srv_sales_large_goods
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_srv_sales_large_goods
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_srv_sales_large_goods
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_srv_sales_large_goods
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_srv_sales_large_goods
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_srv_sales_large_goods
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_srv_sales_large_goods
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_srv_sales_large_goods
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsIdIsNull() {
            addCriterion("large_goods_id is null");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsIdIsNotNull() {
            addCriterion("large_goods_id is not null");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsIdEqualTo(String value) {
            addCriterion("large_goods_id =", value, "largeGoodsId");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsIdNotEqualTo(String value) {
            addCriterion("large_goods_id <>", value, "largeGoodsId");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsIdGreaterThan(String value) {
            addCriterion("large_goods_id >", value, "largeGoodsId");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsIdGreaterThanOrEqualTo(String value) {
            addCriterion("large_goods_id >=", value, "largeGoodsId");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsIdLessThan(String value) {
            addCriterion("large_goods_id <", value, "largeGoodsId");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsIdLessThanOrEqualTo(String value) {
            addCriterion("large_goods_id <=", value, "largeGoodsId");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsIdLike(String value) {
            addCriterion("large_goods_id like", value, "largeGoodsId");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsIdNotLike(String value) {
            addCriterion("large_goods_id not like", value, "largeGoodsId");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsIdIn(List<String> values) {
            addCriterion("large_goods_id in", values, "largeGoodsId");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsIdNotIn(List<String> values) {
            addCriterion("large_goods_id not in", values, "largeGoodsId");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsIdBetween(String value1, String value2) {
            addCriterion("large_goods_id between", value1, value2, "largeGoodsId");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsIdNotBetween(String value1, String value2) {
            addCriterion("large_goods_id not between", value1, value2, "largeGoodsId");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsNameIsNull() {
            addCriterion("large_goods_name is null");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsNameIsNotNull() {
            addCriterion("large_goods_name is not null");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsNameEqualTo(String value) {
            addCriterion("large_goods_name =", value, "largeGoodsName");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsNameNotEqualTo(String value) {
            addCriterion("large_goods_name <>", value, "largeGoodsName");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsNameGreaterThan(String value) {
            addCriterion("large_goods_name >", value, "largeGoodsName");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsNameGreaterThanOrEqualTo(String value) {
            addCriterion("large_goods_name >=", value, "largeGoodsName");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsNameLessThan(String value) {
            addCriterion("large_goods_name <", value, "largeGoodsName");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsNameLessThanOrEqualTo(String value) {
            addCriterion("large_goods_name <=", value, "largeGoodsName");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsNameLike(String value) {
            addCriterion("large_goods_name like", value, "largeGoodsName");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsNameNotLike(String value) {
            addCriterion("large_goods_name not like", value, "largeGoodsName");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsNameIn(List<String> values) {
            addCriterion("large_goods_name in", values, "largeGoodsName");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsNameNotIn(List<String> values) {
            addCriterion("large_goods_name not in", values, "largeGoodsName");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsNameBetween(String value1, String value2) {
            addCriterion("large_goods_name between", value1, value2, "largeGoodsName");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsNameNotBetween(String value1, String value2) {
            addCriterion("large_goods_name not between", value1, value2, "largeGoodsName");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsIdListIsNull() {
            addCriterion("large_goods_id_list is null");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsIdListIsNotNull() {
            addCriterion("large_goods_id_list is not null");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsIdListEqualTo(String value) {
            addCriterion("large_goods_id_list =", value, "largeGoodsIdList");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsIdListNotEqualTo(String value) {
            addCriterion("large_goods_id_list <>", value, "largeGoodsIdList");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsIdListGreaterThan(String value) {
            addCriterion("large_goods_id_list >", value, "largeGoodsIdList");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsIdListGreaterThanOrEqualTo(String value) {
            addCriterion("large_goods_id_list >=", value, "largeGoodsIdList");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsIdListLessThan(String value) {
            addCriterion("large_goods_id_list <", value, "largeGoodsIdList");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsIdListLessThanOrEqualTo(String value) {
            addCriterion("large_goods_id_list <=", value, "largeGoodsIdList");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsIdListLike(String value) {
            addCriterion("large_goods_id_list like", value, "largeGoodsIdList");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsIdListNotLike(String value) {
            addCriterion("large_goods_id_list not like", value, "largeGoodsIdList");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsIdListIn(List<String> values) {
            addCriterion("large_goods_id_list in", values, "largeGoodsIdList");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsIdListNotIn(List<String> values) {
            addCriterion("large_goods_id_list not in", values, "largeGoodsIdList");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsIdListBetween(String value1, String value2) {
            addCriterion("large_goods_id_list between", value1, value2, "largeGoodsIdList");
            return (Criteria) this;
        }

        public Criteria andLargeGoodsIdListNotBetween(String value1, String value2) {
            addCriterion("large_goods_id_list not between", value1, value2, "largeGoodsIdList");
            return (Criteria) this;
        }

        public Criteria andOrgIdIsNull() {
            addCriterion("org_id is null");
            return (Criteria) this;
        }

        public Criteria andOrgIdIsNotNull() {
            addCriterion("org_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrgIdEqualTo(String value) {
            addCriterion("org_id =", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotEqualTo(String value) {
            addCriterion("org_id <>", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdGreaterThan(String value) {
            addCriterion("org_id >", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdGreaterThanOrEqualTo(String value) {
            addCriterion("org_id >=", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLessThan(String value) {
            addCriterion("org_id <", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLessThanOrEqualTo(String value) {
            addCriterion("org_id <=", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLike(String value) {
            addCriterion("org_id like", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotLike(String value) {
            addCriterion("org_id not like", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdIn(List<String> values) {
            addCriterion("org_id in", values, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotIn(List<String> values) {
            addCriterion("org_id not in", values, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdBetween(String value1, String value2) {
            addCriterion("org_id between", value1, value2, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotBetween(String value1, String value2) {
            addCriterion("org_id not between", value1, value2, "orgId");
            return (Criteria) this;
        }

        public Criteria andShipmentIdIsNull() {
            addCriterion("shipment_id is null");
            return (Criteria) this;
        }

        public Criteria andShipmentIdIsNotNull() {
            addCriterion("shipment_id is not null");
            return (Criteria) this;
        }

        public Criteria andShipmentIdEqualTo(Integer value) {
            addCriterion("shipment_id =", value, "shipmentId");
            return (Criteria) this;
        }

        public Criteria andShipmentIdNotEqualTo(Integer value) {
            addCriterion("shipment_id <>", value, "shipmentId");
            return (Criteria) this;
        }

        public Criteria andShipmentIdGreaterThan(Integer value) {
            addCriterion("shipment_id >", value, "shipmentId");
            return (Criteria) this;
        }

        public Criteria andShipmentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("shipment_id >=", value, "shipmentId");
            return (Criteria) this;
        }

        public Criteria andShipmentIdLessThan(Integer value) {
            addCriterion("shipment_id <", value, "shipmentId");
            return (Criteria) this;
        }

        public Criteria andShipmentIdLessThanOrEqualTo(Integer value) {
            addCriterion("shipment_id <=", value, "shipmentId");
            return (Criteria) this;
        }

        public Criteria andShipmentIdIn(List<Integer> values) {
            addCriterion("shipment_id in", values, "shipmentId");
            return (Criteria) this;
        }

        public Criteria andShipmentIdNotIn(List<Integer> values) {
            addCriterion("shipment_id not in", values, "shipmentId");
            return (Criteria) this;
        }

        public Criteria andShipmentIdBetween(Integer value1, Integer value2) {
            addCriterion("shipment_id between", value1, value2, "shipmentId");
            return (Criteria) this;
        }

        public Criteria andShipmentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("shipment_id not between", value1, value2, "shipmentId");
            return (Criteria) this;
        }

        public Criteria andShipmentExpenseIsNull() {
            addCriterion("shipment_expense is null");
            return (Criteria) this;
        }

        public Criteria andShipmentExpenseIsNotNull() {
            addCriterion("shipment_expense is not null");
            return (Criteria) this;
        }

        public Criteria andShipmentExpenseEqualTo(BigDecimal value) {
            addCriterion("shipment_expense =", value, "shipmentExpense");
            return (Criteria) this;
        }

        public Criteria andShipmentExpenseNotEqualTo(BigDecimal value) {
            addCriterion("shipment_expense <>", value, "shipmentExpense");
            return (Criteria) this;
        }

        public Criteria andShipmentExpenseGreaterThan(BigDecimal value) {
            addCriterion("shipment_expense >", value, "shipmentExpense");
            return (Criteria) this;
        }

        public Criteria andShipmentExpenseGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("shipment_expense >=", value, "shipmentExpense");
            return (Criteria) this;
        }

        public Criteria andShipmentExpenseLessThan(BigDecimal value) {
            addCriterion("shipment_expense <", value, "shipmentExpense");
            return (Criteria) this;
        }

        public Criteria andShipmentExpenseLessThanOrEqualTo(BigDecimal value) {
            addCriterion("shipment_expense <=", value, "shipmentExpense");
            return (Criteria) this;
        }

        public Criteria andShipmentExpenseIn(List<BigDecimal> values) {
            addCriterion("shipment_expense in", values, "shipmentExpense");
            return (Criteria) this;
        }

        public Criteria andShipmentExpenseNotIn(List<BigDecimal> values) {
            addCriterion("shipment_expense not in", values, "shipmentExpense");
            return (Criteria) this;
        }

        public Criteria andShipmentExpenseBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("shipment_expense between", value1, value2, "shipmentExpense");
            return (Criteria) this;
        }

        public Criteria andShipmentExpenseNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("shipment_expense not between", value1, value2, "shipmentExpense");
            return (Criteria) this;
        }

        public Criteria andUpdatePersonIsNull() {
            addCriterion("update_person is null");
            return (Criteria) this;
        }

        public Criteria andUpdatePersonIsNotNull() {
            addCriterion("update_person is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatePersonEqualTo(Long value) {
            addCriterion("update_person =", value, "updatePerson");
            return (Criteria) this;
        }

        public Criteria andUpdatePersonNotEqualTo(Long value) {
            addCriterion("update_person <>", value, "updatePerson");
            return (Criteria) this;
        }

        public Criteria andUpdatePersonGreaterThan(Long value) {
            addCriterion("update_person >", value, "updatePerson");
            return (Criteria) this;
        }

        public Criteria andUpdatePersonGreaterThanOrEqualTo(Long value) {
            addCriterion("update_person >=", value, "updatePerson");
            return (Criteria) this;
        }

        public Criteria andUpdatePersonLessThan(Long value) {
            addCriterion("update_person <", value, "updatePerson");
            return (Criteria) this;
        }

        public Criteria andUpdatePersonLessThanOrEqualTo(Long value) {
            addCriterion("update_person <=", value, "updatePerson");
            return (Criteria) this;
        }

        public Criteria andUpdatePersonIn(List<Long> values) {
            addCriterion("update_person in", values, "updatePerson");
            return (Criteria) this;
        }

        public Criteria andUpdatePersonNotIn(List<Long> values) {
            addCriterion("update_person not in", values, "updatePerson");
            return (Criteria) this;
        }

        public Criteria andUpdatePersonBetween(Long value1, Long value2) {
            addCriterion("update_person between", value1, value2, "updatePerson");
            return (Criteria) this;
        }

        public Criteria andUpdatePersonNotBetween(Long value1, Long value2) {
            addCriterion("update_person not between", value1, value2, "updatePerson");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("add_time is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("add_time is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("add_time =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("add_time <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("add_time >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("add_time >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("add_time <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("add_time <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<Date> values) {
            addCriterion("add_time in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<Date> values) {
            addCriterion("add_time not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("add_time between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("add_time not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andIsBatchIsNull() {
            addCriterion("is_batch is null");
            return (Criteria) this;
        }

        public Criteria andIsBatchIsNotNull() {
            addCriterion("is_batch is not null");
            return (Criteria) this;
        }

        public Criteria andIsBatchEqualTo(String value) {
            addCriterion("is_batch =", value, "isBatch");
            return (Criteria) this;
        }

        public Criteria andIsBatchNotEqualTo(String value) {
            addCriterion("is_batch <>", value, "isBatch");
            return (Criteria) this;
        }

        public Criteria andIsBatchGreaterThan(String value) {
            addCriterion("is_batch >", value, "isBatch");
            return (Criteria) this;
        }

        public Criteria andIsBatchGreaterThanOrEqualTo(String value) {
            addCriterion("is_batch >=", value, "isBatch");
            return (Criteria) this;
        }

        public Criteria andIsBatchLessThan(String value) {
            addCriterion("is_batch <", value, "isBatch");
            return (Criteria) this;
        }

        public Criteria andIsBatchLessThanOrEqualTo(String value) {
            addCriterion("is_batch <=", value, "isBatch");
            return (Criteria) this;
        }

        public Criteria andIsBatchLike(String value) {
            addCriterion("is_batch like", value, "isBatch");
            return (Criteria) this;
        }

        public Criteria andIsBatchNotLike(String value) {
            addCriterion("is_batch not like", value, "isBatch");
            return (Criteria) this;
        }

        public Criteria andIsBatchIn(List<String> values) {
            addCriterion("is_batch in", values, "isBatch");
            return (Criteria) this;
        }

        public Criteria andIsBatchNotIn(List<String> values) {
            addCriterion("is_batch not in", values, "isBatch");
            return (Criteria) this;
        }

        public Criteria andIsBatchBetween(String value1, String value2) {
            addCriterion("is_batch between", value1, value2, "isBatch");
            return (Criteria) this;
        }

        public Criteria andIsBatchNotBetween(String value1, String value2) {
            addCriterion("is_batch not between", value1, value2, "isBatch");
            return (Criteria) this;
        }

        public Criteria andIsEnableIsNull() {
            addCriterion("is_enable is null");
            return (Criteria) this;
        }

        public Criteria andIsEnableIsNotNull() {
            addCriterion("is_enable is not null");
            return (Criteria) this;
        }

        public Criteria andIsEnableEqualTo(String value) {
            addCriterion("is_enable =", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableNotEqualTo(String value) {
            addCriterion("is_enable <>", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableGreaterThan(String value) {
            addCriterion("is_enable >", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableGreaterThanOrEqualTo(String value) {
            addCriterion("is_enable >=", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableLessThan(String value) {
            addCriterion("is_enable <", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableLessThanOrEqualTo(String value) {
            addCriterion("is_enable <=", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableLike(String value) {
            addCriterion("is_enable like", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableNotLike(String value) {
            addCriterion("is_enable not like", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableIn(List<String> values) {
            addCriterion("is_enable in", values, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableNotIn(List<String> values) {
            addCriterion("is_enable not in", values, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableBetween(String value1, String value2) {
            addCriterion("is_enable between", value1, value2, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableNotBetween(String value1, String value2) {
            addCriterion("is_enable not between", value1, value2, "isEnable");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_srv_sales_large_goods
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_srv_sales_large_goods
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}