package com.ning.dao;

import com.ning.dao.SalesLargeGoods;
import com.ning.dao.SalesLargeGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface SalesLargeGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_srv_sales_large_goods
     *
     * @mbggenerated
     */
    int countByExample(SalesLargeGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_srv_sales_large_goods
     *
     * @mbggenerated
     */
    @Delete({
        "delete from t_srv_sales_large_goods",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_srv_sales_large_goods
     *
     * @mbggenerated
     */
    @Insert({
        "insert into t_srv_sales_large_goods (id, large_goods_id, ",
        "large_goods_name, large_goods_id_list, ",
        "org_id, shipment_id, ",
        "shipment_expense, update_person, ",
        "add_time, update_time, ",
        "is_batch, is_enable, remark)",
        "values (#{id,jdbcType=BIGINT}, #{largeGoodsId,jdbcType=VARCHAR}, ",
        "#{largeGoodsName,jdbcType=VARCHAR}, #{largeGoodsIdList,jdbcType=VARCHAR}, ",
        "#{orgId,jdbcType=VARCHAR}, #{shipmentId,jdbcType=INTEGER}, ",
        "#{shipmentExpense,jdbcType=DECIMAL}, #{updatePerson,jdbcType=BIGINT}, ",
        "#{addTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{isBatch,jdbcType=CHAR}, #{isEnable,jdbcType=CHAR}, #{remark,jdbcType=VARCHAR})"
    })
    int insert(SalesLargeGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_srv_sales_large_goods
     *
     * @mbggenerated
     */
    int insertSelective(SalesLargeGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_srv_sales_large_goods
     *
     * @mbggenerated
     */
    List<SalesLargeGoods> selectByExample(SalesLargeGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_srv_sales_large_goods
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, large_goods_id, large_goods_name, large_goods_id_list, org_id, shipment_id, ",
        "shipment_expense, update_person, add_time, update_time, is_batch, is_enable, ",
        "remark",
        "from t_srv_sales_large_goods",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    SalesLargeGoods selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_srv_sales_large_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SalesLargeGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_srv_sales_large_goods
     *
     * @mbggenerated
     */
    @Update({
        "update t_srv_sales_large_goods",
        "set large_goods_id = #{largeGoodsId,jdbcType=VARCHAR},",
          "large_goods_name = #{largeGoodsName,jdbcType=VARCHAR},",
          "large_goods_id_list = #{largeGoodsIdList,jdbcType=VARCHAR},",
          "org_id = #{orgId,jdbcType=VARCHAR},",
          "shipment_id = #{shipmentId,jdbcType=INTEGER},",
          "shipment_expense = #{shipmentExpense,jdbcType=DECIMAL},",
          "update_person = #{updatePerson,jdbcType=BIGINT},",
          "add_time = #{addTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "is_batch = #{isBatch,jdbcType=CHAR},",
          "is_enable = #{isEnable,jdbcType=CHAR},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(SalesLargeGoods record);
}