package com.ning.dao;

import java.math.BigDecimal;
import java.util.Date;

public class SalesLargeGoods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_srv_sales_large_goods.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_srv_sales_large_goods.large_goods_id
     *
     * @mbggenerated
     */
    private String largeGoodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_srv_sales_large_goods.large_goods_name
     *
     * @mbggenerated
     */
    private String largeGoodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_srv_sales_large_goods.large_goods_id_list
     *
     * @mbggenerated
     */
    private String largeGoodsIdList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_srv_sales_large_goods.org_id
     *
     * @mbggenerated
     */
    private String orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_srv_sales_large_goods.shipment_id
     *
     * @mbggenerated
     */
    private Integer shipmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_srv_sales_large_goods.shipment_expense
     *
     * @mbggenerated
     */
    private BigDecimal shipmentExpense;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_srv_sales_large_goods.update_person
     *
     * @mbggenerated
     */
    private Long updatePerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_srv_sales_large_goods.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_srv_sales_large_goods.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_srv_sales_large_goods.is_batch
     *
     * @mbggenerated
     */
    private String isBatch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_srv_sales_large_goods.is_enable
     *
     * @mbggenerated
     */
    private String isEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_srv_sales_large_goods.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_srv_sales_large_goods
     *
     * @mbggenerated
     */
    public SalesLargeGoods(Long id, String largeGoodsId, String largeGoodsName, String largeGoodsIdList, String orgId, Integer shipmentId, BigDecimal shipmentExpense, Long updatePerson, Date addTime, Date updateTime, String isBatch, String isEnable, String remark) {
        this.id = id;
        this.largeGoodsId = largeGoodsId;
        this.largeGoodsName = largeGoodsName;
        this.largeGoodsIdList = largeGoodsIdList;
        this.orgId = orgId;
        this.shipmentId = shipmentId;
        this.shipmentExpense = shipmentExpense;
        this.updatePerson = updatePerson;
        this.addTime = addTime;
        this.updateTime = updateTime;
        this.isBatch = isBatch;
        this.isEnable = isEnable;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_srv_sales_large_goods
     *
     * @mbggenerated
     */
    public SalesLargeGoods() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_srv_sales_large_goods.id
     *
     * @return the value of t_srv_sales_large_goods.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_srv_sales_large_goods.id
     *
     * @param id the value for t_srv_sales_large_goods.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_srv_sales_large_goods.large_goods_id
     *
     * @return the value of t_srv_sales_large_goods.large_goods_id
     *
     * @mbggenerated
     */
    public String getLargeGoodsId() {
        return largeGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_srv_sales_large_goods.large_goods_id
     *
     * @param largeGoodsId the value for t_srv_sales_large_goods.large_goods_id
     *
     * @mbggenerated
     */
    public void setLargeGoodsId(String largeGoodsId) {
        this.largeGoodsId = largeGoodsId == null ? null : largeGoodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_srv_sales_large_goods.large_goods_name
     *
     * @return the value of t_srv_sales_large_goods.large_goods_name
     *
     * @mbggenerated
     */
    public String getLargeGoodsName() {
        return largeGoodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_srv_sales_large_goods.large_goods_name
     *
     * @param largeGoodsName the value for t_srv_sales_large_goods.large_goods_name
     *
     * @mbggenerated
     */
    public void setLargeGoodsName(String largeGoodsName) {
        this.largeGoodsName = largeGoodsName == null ? null : largeGoodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_srv_sales_large_goods.large_goods_id_list
     *
     * @return the value of t_srv_sales_large_goods.large_goods_id_list
     *
     * @mbggenerated
     */
    public String getLargeGoodsIdList() {
        return largeGoodsIdList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_srv_sales_large_goods.large_goods_id_list
     *
     * @param largeGoodsIdList the value for t_srv_sales_large_goods.large_goods_id_list
     *
     * @mbggenerated
     */
    public void setLargeGoodsIdList(String largeGoodsIdList) {
        this.largeGoodsIdList = largeGoodsIdList == null ? null : largeGoodsIdList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_srv_sales_large_goods.org_id
     *
     * @return the value of t_srv_sales_large_goods.org_id
     *
     * @mbggenerated
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_srv_sales_large_goods.org_id
     *
     * @param orgId the value for t_srv_sales_large_goods.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_srv_sales_large_goods.shipment_id
     *
     * @return the value of t_srv_sales_large_goods.shipment_id
     *
     * @mbggenerated
     */
    public Integer getShipmentId() {
        return shipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_srv_sales_large_goods.shipment_id
     *
     * @param shipmentId the value for t_srv_sales_large_goods.shipment_id
     *
     * @mbggenerated
     */
    public void setShipmentId(Integer shipmentId) {
        this.shipmentId = shipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_srv_sales_large_goods.shipment_expense
     *
     * @return the value of t_srv_sales_large_goods.shipment_expense
     *
     * @mbggenerated
     */
    public BigDecimal getShipmentExpense() {
        return shipmentExpense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_srv_sales_large_goods.shipment_expense
     *
     * @param shipmentExpense the value for t_srv_sales_large_goods.shipment_expense
     *
     * @mbggenerated
     */
    public void setShipmentExpense(BigDecimal shipmentExpense) {
        this.shipmentExpense = shipmentExpense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_srv_sales_large_goods.update_person
     *
     * @return the value of t_srv_sales_large_goods.update_person
     *
     * @mbggenerated
     */
    public Long getUpdatePerson() {
        return updatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_srv_sales_large_goods.update_person
     *
     * @param updatePerson the value for t_srv_sales_large_goods.update_person
     *
     * @mbggenerated
     */
    public void setUpdatePerson(Long updatePerson) {
        this.updatePerson = updatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_srv_sales_large_goods.add_time
     *
     * @return the value of t_srv_sales_large_goods.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_srv_sales_large_goods.add_time
     *
     * @param addTime the value for t_srv_sales_large_goods.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_srv_sales_large_goods.update_time
     *
     * @return the value of t_srv_sales_large_goods.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_srv_sales_large_goods.update_time
     *
     * @param updateTime the value for t_srv_sales_large_goods.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_srv_sales_large_goods.is_batch
     *
     * @return the value of t_srv_sales_large_goods.is_batch
     *
     * @mbggenerated
     */
    public String getIsBatch() {
        return isBatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_srv_sales_large_goods.is_batch
     *
     * @param isBatch the value for t_srv_sales_large_goods.is_batch
     *
     * @mbggenerated
     */
    public void setIsBatch(String isBatch) {
        this.isBatch = isBatch == null ? null : isBatch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_srv_sales_large_goods.is_enable
     *
     * @return the value of t_srv_sales_large_goods.is_enable
     *
     * @mbggenerated
     */
    public String getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_srv_sales_large_goods.is_enable
     *
     * @param isEnable the value for t_srv_sales_large_goods.is_enable
     *
     * @mbggenerated
     */
    public void setIsEnable(String isEnable) {
        this.isEnable = isEnable == null ? null : isEnable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_srv_sales_large_goods.remark
     *
     * @return the value of t_srv_sales_large_goods.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_srv_sales_large_goods.remark
     *
     * @param remark the value for t_srv_sales_large_goods.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}