package com.ning.dao;

import java.util.Date;

public class Tool {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tools.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tools.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tools.tool_name
     *
     * @mbggenerated
     */
    private String toolName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tools.tool_icon
     *
     * @mbggenerated
     */
    private String toolIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tools.tool_url
     *
     * @mbggenerated
     */
    private String toolUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tools.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tools.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tools.create_person
     *
     * @mbggenerated
     */
    private String createPerson;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tools
     *
     * @mbggenerated
     */
    public Tool(Integer id, String type, String toolName, String toolIcon, String toolUrl, Date createTime, Date updateTime, String createPerson) {
        this.id = id;
        this.type = type;
        this.toolName = toolName;
        this.toolIcon = toolIcon;
        this.toolUrl = toolUrl;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tools
     *
     * @mbggenerated
     */
    public Tool() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tools.id
     *
     * @return the value of tools.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tools.id
     *
     * @param id the value for tools.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tools.type
     *
     * @return the value of tools.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tools.type
     *
     * @param type the value for tools.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tools.tool_name
     *
     * @return the value of tools.tool_name
     *
     * @mbggenerated
     */
    public String getToolName() {
        return toolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tools.tool_name
     *
     * @param toolName the value for tools.tool_name
     *
     * @mbggenerated
     */
    public void setToolName(String toolName) {
        this.toolName = toolName == null ? null : toolName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tools.tool_icon
     *
     * @return the value of tools.tool_icon
     *
     * @mbggenerated
     */
    public String getToolIcon() {
        return toolIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tools.tool_icon
     *
     * @param toolIcon the value for tools.tool_icon
     *
     * @mbggenerated
     */
    public void setToolIcon(String toolIcon) {
        this.toolIcon = toolIcon == null ? null : toolIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tools.tool_url
     *
     * @return the value of tools.tool_url
     *
     * @mbggenerated
     */
    public String getToolUrl() {
        return toolUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tools.tool_url
     *
     * @param toolUrl the value for tools.tool_url
     *
     * @mbggenerated
     */
    public void setToolUrl(String toolUrl) {
        this.toolUrl = toolUrl == null ? null : toolUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tools.create_time
     *
     * @return the value of tools.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tools.create_time
     *
     * @param createTime the value for tools.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tools.update_time
     *
     * @return the value of tools.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tools.update_time
     *
     * @param updateTime the value for tools.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tools.create_person
     *
     * @return the value of tools.create_person
     *
     * @mbggenerated
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tools.create_person
     *
     * @param createPerson the value for tools.create_person
     *
     * @mbggenerated
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson == null ? null : createPerson.trim();
    }
}